# Generated by Django 3.2.12 on 2022-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(max_length=25)),
                ('name', models.CharField(max_length=256)),
                ('domain', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=50)),
                ('year_founded', models.IntegerField(max_length=25)),
                ('industry', models.CharField(max_length=256)),
                ('size_range', models.CharField(max_length=256)),
                ('locality', models.TextField()),
                ('country', models.CharField(max_length=256)),
                ('linkedin_url', models.TextField()),
                ('current_employee_estimate', models.IntegerField(max_length=25)),
                ('total_employee_estimate', models.IntegerField(max_length=25)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'company_data',
            },
        ),
    ]
