# Generated by Django 3.2.12 on 2022-02-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='current_employee_estimate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='total_employee_estimate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='year_founded',
            field=models.IntegerField(),
        ),
    ]
