# Generated by Django 3.2.12 on 2022-02-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0002_auto_20220213_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='phone',
        ),
    ]
