# Generated by Django 3.2.12 on 2022-02-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0003_remove_companydata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='count',
            field=models.CharField(max_length=256),
        ),
    ]
