# Generated by Django 3.2.12 on 2022-02-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0004_alter_companydata_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='year_founded',
            field=models.CharField(max_length=256),
        ),
    ]
