# Generated by Django 3.2.12 on 2022-02-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0006_auto_20220214_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='locality',
        ),
    ]
