# Generated by Django 3.2.12 on 2022-02-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0007_remove_companydata_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
